---
- name: add k8s repo
  yum_repository:
    name: k8s
    description: k8s repositories
    baseurl: https://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-x86_64/ 
    gpgcheck: no
    enabled: yes

- name: install kubeadm,kubelet,kubectl
  yum: 
    name: 
      - kubelet-{{ k8s_version }}
      - kubeadm-{{ k8s_version }} 
      - kubectl-{{ k8s_version }}
    state: present

- name: enable kubelet service
  service: 
    name: kubelet
    state: started
    enabled: yes

#- name: copy kube-vip config file
#  template:
#    src: config.yaml.j2
#    dest: /etc/kube-vip/ 

#- name: static pod vip
#  copy:
#    name: kube-vip.yaml
#    dest: /etc/kubernetes/manifests/

- name: copy init file template
  template:
    src: initconfig.yaml.j2
    dest: /root/initconfig.yaml
  become: true

- name: test if k8s installed
  shell: KUBECONFIG=/etc/kubernetes/admin.conf kubectl get node
  register: result
  ignore_errors: True
  changed_when: false
  
- name: install k8s master
  command: kubeadm init --config /root/initconfig.yaml 
  when: result is failed

- name: set env 
  copy:
    src: k8s.sh
    dest: /etc/profile.d/

- name: copy calico file
  copy: 
    src: calico.yaml
    dest: /root

- name: install calico 
  shell: KUBECONFIG=/etc/kubernetes/admin.conf kubectl apply -f /root/calico.yaml
  register: calico_result
  changed_when: "calico_result.rc != 0"

- name: install bash-completion
  yum:
    name: bash-completion
    state: present

- name: kubectl command completion
  shell: KUBECONFIG=/etc/kubernetes/admin.conf kubectl completion bash > /etc/bash_completion.d/kubectl
