---
- name: create docker file dest
  file:
    dest: "{{ file_dest }}"
    state: directory

- name: copy docker-compose file to dest host
  template:
    src: rabbitmq.yml.j2
    dest: "{{ file_dest }}/rabbitmq.yml"

- name: create dir
  file:
    dest: "{{ item }}"
    state: directory
    owner: "999"
    group: "999"
  with_items:
    - "{{ service_dest }}/data"
    - "{{ service_dest }}/config"

- name: copy enabled_plugins file
  copy:
    src: enabled_plugins
    dest: "{{ service_dest }}/config/"
    owner: "999"
    group: "999"

- name: start service
  command: docker-compose -f {{ file_dest }}/rabbitmq.yml up -d
