---
- hosts: all
  remote_user: root
  roles:
  - mysql

#- hosts: lb_servers
#  remote_user: root
#  roles:
#  - lb-nginx
#
#- hosts: backend_servers
#  remote_user: root
#  roles:
#  - mysql
#
#- hosts: memcached_servers
#  remote_user: root
#  roles:
#  - memcached
#
