---
# tasks file for common
- name: install chrony service
  yum:
    name: chrony
    state: present
- name: config chronyd
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  notify:
    - restart_chronyd

- name: start service
  service:
    name: chronyd
    state: started
    enabled: yes
